import { Component, inject, signal } from '@angular/core';
import { CommonService } from '../services/common.service';
import { NxAiModelPlayground, NxModelPlaygroundRunParams, NxAiModel } from '../../../../../dist/components';
import { DemoSection } from '../shared/demo-section/demo-section';

const MODELS: NxAiModel[] = [
  { id: 'nexium-fast', label: 'Nexium Fast', description: 'Optimized for low latency.', badge: 'Fast' },
  { id: 'nexium-pro', label: 'Nexium Pro', description: 'Stronger reasoning for complex requests.', badge: 'Most capable' },
  { id: 'nexium-code', label: 'Nexium Code', description: 'Tuned for reading and writing source code.' },
];

@Component({
  selector: 'app-ui-ai-model-playground-demo',
  imports: [NxAiModelPlayground, DemoSection],
  templateUrl: './ui-ai-model-playground-demo.html',
  styleUrl: './ui-ai-model-playground-demo.scss',
})
export class UiAiModelPlaygroundDemo {
  importCode = `import { NxAiModelPlayground } from 'nexium-ui';`;

  public commonService = inject(CommonService);

  models = MODELS;

  // Signals rather than plain properties: the simulated response lands inside a setTimeout,
  // outside any Angular-dispatched event, so in a zoneless app a plain property write wouldn't
  // get picked up until some unrelated click happened to trigger a re-render.
  response = signal<string | undefined>(undefined);
  isRunning = signal(false);

  onRun(params: NxModelPlaygroundRunParams): void {
    this.isRunning.set(true);
    this.response.set(undefined);

    setTimeout(() => {
      this.response.set(
        `**[Simulated response from ${params.modelId}]**\n\nWith temperature=${params.temperature}, topP=${params.topP}, and a ${params.maxTokens}-token budget, here is a canned reply to:\n\n> ${params.prompt}\n\nThis text is not generated by a real model - wire up (run) to your own API call and feed the result back through [response].`,
      );
      this.isRunning.set(false);
    }, 1200);
  }

  basicCode = `<nx-ai-model-playground
    [models]="models"
    [response]="response()"
    [isRunning]="isRunning()"
    (run)="onRun($event)">
</nx-ai-model-playground>`;

  basicTs = `models = [
  { id: 'nexium-fast', label: 'Nexium Fast', badge: 'Fast' },
  { id: 'nexium-pro', label: 'Nexium Pro', badge: 'Most capable' },
];

response?: string;
isRunning = false;

// NxAiModelPlayground never calls a real API itself - (run) emits the full parameter set and
// this demo simulates a delayed canned response to show the loop working end to end.
onRun(params: { modelId: string; prompt: string; temperature: number; maxTokens: number; topP: number }): void {
  this.isRunning = true;
  this.response = undefined;

  setTimeout(() => {
    this.response = \`Simulated response from \${params.modelId}...\`;
    this.isRunning = false;
  }, 1200);
}`;

  prefilledResponse = 'A **binary search** runs in `O(log n)` time by repeatedly halving the search range - compare the middle element, then recurse into the half that could still contain the target.';
  prefilledCode = `<nx-ai-model-playground [models]="models" [response]="prefilledResponse"></nx-ai-model-playground>`;
  prefilledTs = `// Feeding a value into [response] directly (with no (run) handler at all) is useful for a
// read-only showcase, or to restore a previous session's last result on reload.
prefilledResponse = 'A binary search runs in O(log n) time...';`;
}
