import { Component, inject, signal } from '@angular/core';
import { CommonService } from '../services/common.service';
import { NxAiChat, NxChatStreamMessage, NxAiModel } from '../../../../../dist/components';
import { DemoSection } from '../shared/demo-section/demo-section';

const MODELS: NxAiModel[] = [
  { id: 'nexium-fast', label: 'Nexium Fast', description: 'Optimized for low latency and everyday tasks.', badge: 'Fast' },
  { id: 'nexium-pro', label: 'Nexium Pro', description: 'Stronger reasoning for complex, multi-step requests.', badge: 'Most capable' },
  { id: 'nexium-mini', label: 'Nexium Mini', description: 'A compact model for simple, high-volume requests.', badge: 'Economical' },
];

const CANNED_REPLIES = [
  "Here's a simulated reply - in a real app this is where your actual API call's response would land.",
  "Sure - happy to help with that. (This is a canned demo reply; nothing was actually sent to a model.)",
  "Good question. This response is only simulated by the demo page, not generated by a real model.",
];

@Component({
  selector: 'app-ui-ai-chat-demo',
  imports: [NxAiChat, DemoSection],
  templateUrl: './ui-ai-chat-demo.html',
  styleUrl: './ui-ai-chat-demo.scss',
})
export class UiAiChatDemo {
  importCode = `import { NxAiChat } from 'nexium-ui';`;

  public commonService = inject(CommonService);

  models = MODELS;
  selectedModelId = signal('nexium-pro');

  // Signals rather than plain properties: the simulated reply lands inside a setTimeout, outside
  // any Angular-dispatched event, so in a zoneless app a plain property write wouldn't get picked
  // up until some unrelated click happened to trigger a re-render.
  messages = signal<NxChatStreamMessage[]>([
    { role: 'user', content: 'Can you summarize what a REST API is in one sentence?' },
    {
      role: 'assistant',
      content:
        'A REST API is a way for applications to communicate over HTTP using standard verbs (GET, POST, PUT, DELETE) against resource-based URLs.',
    },
  ]);
  streaming = signal(false);

  onModelChange(id: string): void {
    this.selectedModelId.set(id);
  }

  onSubmit(text: string): void {
    this.messages.update((current) => [...current, { role: 'user', content: text }]);
    this.streaming.set(true);

    const reply = CANNED_REPLIES[Math.floor(Math.random() * CANNED_REPLIES.length)];
    setTimeout(() => {
      this.messages.update((current) => [...current, { role: 'assistant', content: reply }]);
    }, 500);
    // streaming stays true a bit longer than the message arrival so nx-chat-stream's reveal
    // animation (driven by `streaming`) has time to play out before this demo turns it off.
    setTimeout(() => {
      this.streaming.set(false);
    }, 500 + reply.length * 10);
  }

  basicCode = `<nx-ai-chat
    [messages]="messages()"
    [streaming]="streaming()"
    [models]="models"
    [(selectedModelId)]="selectedModelId"
    (submit)="onSubmit($event)">
</nx-ai-chat>`;

  basicTs = `models = [
  { id: 'nexium-fast', label: 'Nexium Fast', badge: 'Fast' },
  { id: 'nexium-pro', label: 'Nexium Pro', badge: 'Most capable' },
];
selectedModelId = 'nexium-pro';
messages: NxChatStreamMessage[] = [
  { role: 'user', content: 'Can you summarize what a REST API is in one sentence?' },
  { role: 'assistant', content: 'A REST API is a way for applications to communicate over HTTP...' },
];
streaming = false;

// NxAiChat never generates a reply itself - it only bubbles the submitted text up via
// (submit). This demo simulates a canned assistant reply after a short delay to show the
// whole loop working; that simulation logic lives here, not inside the component.
onSubmit(text: string): void {
  this.messages = [...this.messages, { role: 'user', content: text }];
  this.streaming = true;

  setTimeout(() => {
    this.messages = [...this.messages, { role: 'assistant', content: 'Here is a simulated reply...' }];
    this.streaming = false;
  }, 900);
}`;

  minimalMessages: NxChatStreamMessage[] = [{ role: 'assistant', content: 'Ask me anything to get started.' }];
  minimalCode = `<nx-ai-chat [messages]="messages" title="Quick Helper"></nx-ai-chat>`;
  minimalTs = `// Omitting [models] entirely hides the header's model selector - useful for a
// single-model assistant that doesn't need to expose model choice to the end user.
messages = [{ role: 'assistant', content: 'Ask me anything to get started.' }];`;
}
