export interface NxSearchItem {
  label: string;
  path?: string;
  group: string;
  type?: 'navigation' | 'action'; // 'action' for commands
  action?: () => void; // For action items
  icon?: string;
}

export const SEARCH_INDEX: NxSearchItem[] = [
  // ===== QUICK LINKS (Top Priority) =====
  { label: 'Playground', path: '/playground', group: 'Quick Links', icon: 'nx-fire' },
  // { label: 'Try It', path: '/try-it', group: 'Quick Links', icon: 'nx-edit' },
  { label: 'NPM Package', path: 'https://www.npmjs.com/package/nexium-ui', group: 'Quick Links', icon: 'nx-external-link' },
  { label: 'GitHub Repository', path: 'https://github.com/nexiumui/nexium-ui', group: 'Quick Links', icon: 'nx-github' },
  { label: 'Changelog', path: '/about/changelog', group: 'Quick Links', icon: 'nx-history' },
  { label: 'Roadmap', path: '/about/roadmap', group: 'Quick Links', icon: 'nx-map' },

  // ===== DOCUMENTATION =====
  { label: 'Getting Started', path: '/getting-started/introduction', group: 'Documentation' },
  { label: 'Installation', path: '/installation/requirements', group: 'Documentation' },
  { label: 'Quick Start', path: '/getting-started/quick-start', group: 'Documentation' },
  { label: 'Configuration', path: '/getting-started/configuration', group: 'Documentation' },
  { label: 'First Component', path: '/getting-started/first-component', group: 'Documentation' },
  { label: 'Migration Guide', path: '/getting-started/migration-guide', group: 'Documentation' },
  { label: 'Design System', path: '/design-system/overview', group: 'Documentation' },
  { label: 'Design Tokens', path: '/design-system/design-tokens', group: 'Documentation' },
  { label: 'Colors', path: '/guide/colors', group: 'Documentation' },
  { label: 'Typography', path: '/guide/typography', group: 'Documentation' },
  { label: 'Spacing', path: '/guide/spacing', group: 'Documentation' },
  { label: 'Border Radius', path: '/design-system/border-radius', group: 'Documentation' },
  { label: 'Shadows', path: '/design-system/shadows', group: 'Documentation' },
  { label: 'Elevation', path: '/design-system/elevation', group: 'Documentation' },
  { label: 'Breakpoints', path: '/design-system/breakpoints', group: 'Documentation' },
  { label: 'Motion & Animation', path: '/design-system/motion-animation', group: 'Documentation' },
  { label: 'Theming', path: '/design-system/overview', group: 'Documentation' },
  { label: 'Accessibility', path: '/accessibility/wcag', group: 'Documentation' },
  { label: 'Keyboard Navigation', path: '/accessibility/keyboard-navigation', group: 'Documentation' },
  { label: 'Screen Readers', path: '/accessibility/screen-readers', group: 'Documentation' },
  { label: 'Focus Management', path: '/accessibility/focus-management', group: 'Documentation' },
  { label: 'ARIA', path: '/accessibility/aria', group: 'Documentation' },
  { label: 'Color Contrast', path: '/accessibility/color-contrast', group: 'Documentation' },
  { label: 'Accessibility Testing Guide', path: '/accessibility/accessibility-testing', group: 'Documentation' },
  { label: 'Internationalization', path: '/internationalization/i18n', group: 'Documentation' },
  { label: 'RTL Support', path: '/guide/rtl-support', group: 'Documentation' },
  { label: 'Translation', path: '/translate', group: 'Documentation' },
  { label: 'Icons', path: '/icons', group: 'Documentation' },
  { label: 'API Reference', path: '/developer/api-reference', group: 'Documentation' },
  { label: 'Angular Compatibility', path: '/developer/angular-compatibility', group: 'Documentation' },
  { label: 'TypeScript', path: '/developer/typescript', group: 'Documentation' },
  { label: 'Developer Configuration', path: '/developer/configuration', group: 'Documentation' },
  { label: 'Theming API', path: '/developer/theming-api', group: 'Documentation' },
  { label: 'Customization', path: '/developer/customization', group: 'Documentation' },
  { label: 'SSR', path: '/developer/ssr', group: 'Documentation' },
  { label: 'Troubleshooting', path: '/developer/troubleshooting', group: 'Documentation' },

  // ===== COMPONENTS - FORMS =====
  { label: 'Button', path: '/button', group: 'Components' },
  { label: 'Input', path: '/input', group: 'Components' },
  { label: 'Textarea', path: '/textarea', group: 'Components' },
  { label: 'Select', path: '/select', group: 'Components' },
  { label: 'AutoComplete', path: '/autocomplete', group: 'Components' },
  { label: 'Combobox', path: '/combobox', group: 'Components' },
  { label: 'Checkbox', path: '/checkbox', group: 'Components' },
  { label: 'Radio', path: '/radio', group: 'Components' },
  { label: 'Switch', path: '/switch', group: 'Components' },
  { label: 'Toggle', path: '/toggle', group: 'Components' },
  { label: 'Segmented Control', path: '/segmented-control', group: 'Components' },
  { label: 'Slider', path: '/slider', group: 'Components' },
  { label: 'Rating', path: '/rating', group: 'Components' },
  { label: 'Mention', path: '/mention', group: 'Components' },
  { label: 'Formula Input', path: '/formula-input', group: 'Components' },
  { label: 'Number Input', path: '/number-input', group: 'Components' },
  { label: 'Input Mask', path: '/input-mask', group: 'Components' },
  { label: 'Password Input', path: '/password-input', group: 'Components' },
  { label: 'Phone Input', path: '/phone-input', group: 'Components' },
  { label: 'Search Input', path: '/search-input', group: 'Components' },
  { label: 'OTP Input', path: '/otp-input', group: 'Components' },
  { label: 'DatePicker', path: '/datepicker', group: 'Components' },
  { label: 'DateRange Picker', path: '/date-range-picker', group: 'Components' },
  { label: 'TimePicker', path: '/time-picker', group: 'Components' },
  { label: 'Event Calendar', path: '/event-calendar', group: 'Components' },
  { label: 'Form Builder', path: '/form-builder', group: 'Components' },
  { label: 'Advanced Form Builder', path: '/form-builder-advanced', group: 'Components' },
  { label: 'Color Picker', path: '/color-picker', group: 'Components' },
  { label: 'Rich Text Editor', path: '/rich-text-editor', group: 'Components' },
  { label: 'Unit Input', path: '/unit-input', group: 'Components' },

  // ===== COMPONENTS - DATA DISPLAY =====
  { label: 'Table', path: '/table', group: 'Components' },
  { label: 'List', path: '/list', group: 'Components' },
  { label: 'Chip', path: '/chip', group: 'Components' },
  { label: 'Badge', path: '/badge', group: 'Components' },
  { label: 'Tag', path: '/tag', group: 'Components' },
  { label: 'Avatar', path: '/avatar', group: 'Components' },
  { label: 'Icon', path: '/icon', group: 'Components' },
  { label: 'Timeline', path: '/timeline', group: 'Components' },
  { label: 'Tree', path: '/tree', group: 'Components' },
  { label: 'Tree Table', path: '/tree-table', group: 'Components' },
  { label: 'Progress Bar', path: '/progress-bar', group: 'Components' },
  { label: 'Spinner', path: '/spinner', group: 'Components' },
  { label: 'Skeleton', path: '/skeleton', group: 'Components' },
  { label: 'Statistic', path: '/statistic', group: 'Components' },
  { label: 'Key-Value List', path: '/key-value-list', group: 'Components' },
  { label: 'Description List', path: '/description-list', group: 'Components' },
  { label: 'Tree Select', path: '/tree-select', group: 'Components' },
  { label: 'Data Grid', path: '/enterprise/data-grid', group: 'Components' },
  { label: 'Document Viewer', path: '/document-viewer', group: 'Components' },
  { label: 'PDF Annotator', path: '/pdf-annotator', group: 'Components' },
  { label: 'Todo List', path: '/todo-list', group: 'Components' },
  { label: 'Notes App', path: '/notes-app', group: 'Components' },
  { label: 'Pinned Item List', path: '/pinned-list', group: 'Components' },
  { label: 'Text Viewer', path: '/text-viewer', group: 'Components' },
  { label: 'PDF Viewer', path: '/pdf-viewer', group: 'Components' },
  { label: 'Word Viewer', path: '/word-viewer', group: 'Components' },
  { label: 'Excel Viewer', path: '/excel-viewer', group: 'Components' },
  { label: 'Markdown Viewer', path: '/markdown-viewer', group: 'Components' },
  { label: 'Text Statistics', path: '/text-statistics', group: 'Components' },

  // ===== COMPONENTS - FEEDBACK =====
  { label: 'Alert', path: '/alert', group: 'Components' },
  { label: 'Message', path: '/message', group: 'Components' },
  { label: 'Toast', path: '/toast', group: 'Components' },
  { label: 'Notification', path: '/notification', group: 'Components' },
  { label: 'Notification Center', path: '/notification-center', group: 'Components' },
  { label: 'Command Palette', path: '/command-palette', group: 'Components' },
  { label: 'Bottom Sheet', path: '/bottom-sheet', group: 'Components' },
  { label: 'Cookie Banner', path: '/cookie-banner', group: 'Components' },
  { label: 'Floating Action Button', path: '/fab', group: 'Components' },
  { label: 'Table of Contents', path: '/table-of-contents', group: 'Components' },
  { label: 'Tooltip', path: '/tooltip', group: 'Components' },
  { label: 'Popover', path: '/popover', group: 'Components' },
  { label: 'Popover Menu', path: '/popover-menu', group: 'Components' },
  { label: 'Hover Card', path: '/hover-card', group: 'Components' },
  { label: 'Modal', path: '/modal', group: 'Components' },
  { label: 'Fullscreen Dialog', path: '/fullscreen-dialog', group: 'Components' },
  { label: 'Dialog', path: '/dialog', group: 'Components' },
  { label: 'Drawer', path: '/drawer', group: 'Components' },
  { label: 'Lightbox', path: '/lightbox', group: 'Components' },
  { label: 'Loading Overlay', path: '/loading-overlay', group: 'Components' },
  { label: 'Tour', path: '/tour', group: 'Components' },
  { label: 'Spotlight', path: '/spotlight', group: 'Components' },
  { label: 'Result', path: '/result', group: 'Components' },
  { label: 'Empty State', path: '/empty-state', group: 'Components' },
  { label: 'Loading', path: '/loading', group: 'Components' },
  { label: 'Loading Button', path: '/loading-button', group: 'Components' },
  { label: 'Status Indicator', path: '/status-indicator', group: 'Components' },
  { label: 'Error State', path: '/error-state', group: 'Components' },
  { label: 'Warning', path: '/warning', group: 'Components' },
  { label: 'Success', path: '/success', group: 'Components' },
  { label: 'Offline State', path: '/offline', group: 'Components' },
  { label: 'Connection Status', path: '/connection-status', group: 'Components' },
  { label: 'Not Found', path: '/not-found', group: 'Components' },
  { label: 'Permission Denied', path: '/permission-denied', group: 'Components' },
  { label: 'Maintenance State', path: '/maintenance-state', group: 'Components' },
  { label: 'Unsaved Changes Dialog', path: '/unsaved-changes-dialog', group: 'Components' },

  // ===== COMPONENTS - PANELS =====
  { label: 'Accordion', path: '/accordion', group: 'Components' },
  { label: 'Tabs', path: '/tabs', group: 'Components' },
  { label: 'Collapse', path: '/collapse', group: 'Components' },
  { label: 'Panel', path: '/panel', group: 'Components' },
  { label: 'Card', path: '/card', group: 'Components' },

  // ===== COMPONENTS - NAVIGATION =====
  { label: 'Breadcrumb', path: '/breadcrumb', group: 'Components' },
  { label: 'Pagination', path: '/pagination', group: 'Components' },
  { label: 'Stepper', path: '/stepper', group: 'Components' },
  { label: 'Sidebar', path: '/sidebar', group: 'Components' },
  { label: 'Menu', path: '/menu', group: 'Components' },
  { label: 'Dropdown Menu', path: '/dropdown-menu', group: 'Components' },
  { label: 'Context Menu', path: '/context-menu', group: 'Components' },
  { label: 'Menubar', path: '/menubar', group: 'Components' },
  { label: 'Mega Menu', path: '/mega-menu', group: 'Components' },
  { label: 'Navbar', path: '/navbar', group: 'Components' },
  { label: 'Bottom Navigation', path: '/bottom-navigation', group: 'Components' },
  { label: 'Back to Top', path: '/back-to-top', group: 'Components' },
  { label: 'Container', path: '/layout/container', group: 'Components' },
  { label: 'Grid', path: '/layout/grid', group: 'Components' },
  { label: 'Flex', path: '/layout/flex', group: 'Components' },
  { label: 'Stack', path: '/layout/stack', group: 'Components' },
  { label: 'Divider', path: '/layout/divider', group: 'Components' },
  { label: 'Spacer', path: '/layout/spacer', group: 'Components' },
  { label: 'Splitter', path: '/layout/splitter', group: 'Components' },
  { label: 'Aspect Ratio', path: '/layout/aspect-ratio', group: 'Components' },
  { label: 'Masonry', path: '/layout/masonry', group: 'Components' },
  { label: 'Resizable', path: '/layout/resizable', group: 'Components' },

  // ===== COMPONENTS - UPLOADS & MEDIA =====
  { label: 'File Upload', path: '/file-upload', group: 'Components' },
  { label: 'Image Upload', path: '/image-upload', group: 'Components' },
  { label: 'Video Upload', path: '/video-upload', group: 'Components' },
  { label: 'Audio Upload', path: '/audio-upload', group: 'Components' },
  { label: 'Document Upload', path: '/document-upload', group: 'Components' },
  { label: 'Dropzone', path: '/dropzone', group: 'Components' },
  { label: 'Gallery', path: '/gallery', group: 'Components' },
  { label: 'Preview', path: '/preview', group: 'Components' },
  { label: 'QR Code', path: '/qr-code', group: 'Components' },
  { label: 'Carousel', path: '/carousel', group: 'Components' },
  { label: 'Image Editor', path: '/image-editor', group: 'Components' },
  { label: 'Document Scanner', path: '/document-scanner', group: 'Components' },

  // ===== PATTERNS & HOW-TO =====
  { label: 'Authentication Pattern', path: '/patterns/authentication', group: 'Patterns' },
  { label: 'CRUD Operations', path: '/patterns/crud', group: 'Patterns' },
  { label: 'Search & Filter', path: '/patterns/search-filter', group: 'Patterns' },
  { label: 'Dashboard', path: '/patterns/dashboard', group: 'Patterns' },
  { label: 'Data Management', path: '/patterns/data-management', group: 'Patterns' },
  { label: 'User Management', path: '/patterns/user-management', group: 'Patterns' },
  { label: 'Error Handling', path: '/patterns/error-handling', group: 'Patterns' },
  { label: 'Portfolio Gallery', path: '/how-to/portfolio-gallery', group: 'Patterns' },
  { label: 'Buy Product', path: '/how-to/buy-product', group: 'Patterns' },
  { label: 'Blog Post', path: '/how-to/blog-post', group: 'Patterns' },
  { label: 'User Onboarding Flow', path: '/how-to/onboarding-flow', group: 'Patterns' },
  { label: 'Multi-Step Signup Wizard', path: '/how-to/signup-wizard', group: 'Patterns' },
  { label: 'Search & Filter Results', path: '/how-to/search-filter', group: 'Patterns' },
  { label: 'File Manager (How To)', path: '/how-to/file-manager', group: 'Patterns' },
  { label: 'Chat / Messaging UI', path: '/how-to/chat-messaging', group: 'Patterns' },
  { label: 'Booking / Reservation Flow', path: '/how-to/booking-flow', group: 'Patterns' },
  { label: 'Job Application Form', path: '/how-to/job-application', group: 'Patterns' },
  { label: 'Support Ticket System', path: '/how-to/support-tickets', group: 'Patterns' },
  { label: 'Real-time Notification Feed', path: '/how-to/notification-feed', group: 'Patterns' },
  { label: 'Kanban Task Board', path: '/how-to/kanban-board', group: 'Patterns' },
  { label: 'Subscription / Plan Comparison', path: '/how-to/plan-comparison', group: 'Patterns' },
  { label: 'Media Player / Video Course', path: '/how-to/media-player', group: 'Patterns' },
  { label: 'Notes App with Search & Categories', path: '/how-to/map-notes', group: 'Patterns' },

  // ===== TESTING & QUALITY =====
  { label: 'Unit Testing', path: '/testing/unit-testing', group: 'Testing' },
  { label: 'Component Testing', path: '/testing/component-testing', group: 'Testing' },
  { label: 'E2E Testing', path: '/testing/e2e-testing', group: 'Testing' },
  { label: 'Visual Testing', path: '/testing/visual-testing', group: 'Testing' },
  { label: 'Accessibility Testing', path: '/testing/accessibility-testing', group: 'Testing' },

  // ===== CHARTS =====
  { label: 'Bar Chart', path: '/charts/bar', group: 'Charts' },
  { label: 'Line Chart', path: '/charts/line', group: 'Charts' },
  { label: 'Pie Chart', path: '/charts/pie', group: 'Charts' },
  { label: 'Area Chart', path: '/charts/area', group: 'Charts' },
  { label: 'Doughnut Chart', path: '/charts/doughnut', group: 'Charts' },
  { label: 'Radar Chart', path: '/charts/radar', group: 'Charts' },
  { label: 'Scatter Chart', path: '/charts/scatter', group: 'Charts' },
  { label: 'Bubble Chart', path: '/charts/bubble', group: 'Charts' },
  { label: 'Gauge Chart', path: '/charts/gauge', group: 'Charts' },
  { label: 'Heatmap', path: '/charts/heatmap', group: 'Charts' },
  { label: 'Funnel Chart', path: '/charts/funnel', group: 'Charts' },
  { label: 'Stacked Bar Chart', path: '/charts/stacked-bar', group: 'Charts' },
  { label: 'Mixed Chart', path: '/charts/mixed', group: 'Charts' },
  { label: 'Sparkline', path: '/charts/sparkline', group: 'Charts' },
  { label: 'Contribution Graph', path: '/charts/contribution-graph', group: 'Charts' },
  { label: 'Sankey Chart', path: '/charts/sankey', group: 'Charts' },
  { label: 'Treemap', path: '/charts/treemap', group: 'Charts' },
  { label: 'Candlestick Chart', path: '/charts/candlestick', group: 'Charts' },
  { label: 'Polar Area', path: '/charts/polar-area', group: 'Charts' },
  { label: 'Sunburst', path: '/charts/sunburst', group: 'Charts' },

  // ===== MISC / APP META =====
  { label: 'Address Input', path: '/address-input', group: 'Components' },
  { label: 'Filter Chip Group', path: '/filter-chip-group', group: 'Components' },
  { label: 'Color Contrast Checker', path: '/color-contrast-checker', group: 'Components' },
  { label: 'Version Badge', path: '/version-badge', group: 'Components' },
  { label: 'Changelog Widget', path: '/changelog-widget', group: 'Components' },
  { label: 'Click Outside', path: '/directives/click-outside', group: 'Components' },
  { label: 'Autofocus', path: '/directives/autofocus', group: 'Components' },
  { label: 'Copy to Clipboard', path: '/directives/copy-to-clipboard', group: 'Components' },
  { label: 'Long Press', path: '/directives/long-press', group: 'Components' },
  { label: 'Debounce Click', path: '/directives/debounce-click', group: 'Components' },
  { label: 'Has Permission', path: '/directives/has-permission', group: 'Components' },
  { label: 'In-View', path: '/directives/in-view', group: 'Components' },
  { label: 'Scroll Lock', path: '/directives/scroll-lock', group: 'Components' },
  { label: 'Focus Trap', path: '/directives/focus-trap', group: 'Components' },
  { label: 'Hotkey', path: '/directives/hotkey', group: 'Components' },
  { label: 'Feature Flag', path: '/directives/feature-flag', group: 'Components' },
  { label: 'Permission Gate', path: '/directives/permission-gate', group: 'Components' },
  { label: 'Activity Timeline', path: '/activity-timeline', group: 'Components' },
  { label: 'Activity Feed', path: '/activity-feed', group: 'Components' },
  { label: 'Audit Timeline', path: '/audit-timeline', group: 'Components' },

  // ===== DEVELOPER & CONTENT DISPLAY =====
  { label: 'Code Block', path: '/code-block', group: 'Components' },
  { label: 'Copyable Text', path: '/copyable-text', group: 'Components' },
  { label: 'Keyboard Shortcut', path: '/keyboard-shortcut', group: 'Components' },
  { label: 'JSON Viewer', path: '/json-viewer', group: 'Components' },
  { label: 'Diff Viewer', path: '/diff-viewer', group: 'Components' },
  { label: 'Before / After', path: '/before-after', group: 'Components' },
  { label: 'JSON Editor', path: '/json-editor', group: 'Components' },
  { label: 'Image Cropper', path: '/image-cropper', group: 'Components' },
  { label: 'Signature Pad', path: '/signature-pad', group: 'Components' },
  { label: 'Transfer Box', path: '/transfer-box', group: 'Components' },
  { label: 'Tag Input', path: '/tag-input', group: 'Components' },

  // ===== NAVIGATION & LAYOUT =====
  { label: 'Navigation Rail', path: '/navigation-rail', group: 'Components' },
  { label: 'Back Button', path: '/back-button', group: 'Components' },
  { label: 'Nav Group', path: '/nav-group', group: 'Components' },
  { label: 'Command Bar', path: '/command-bar', group: 'Components' },
  { label: 'Navigation Progress', path: '/navigation-progress', group: 'Components' },
  { label: 'App Shell', path: '/layout/app-shell', group: 'Components' },
  { label: 'Page Header', path: '/layout/page-header', group: 'Components' },
  { label: 'Page Actions', path: '/layout/page-actions', group: 'Components' },
  { label: 'Responsive Preview', path: '/layout/responsive-preview', group: 'Components' },
  { label: 'Device Frame', path: '/layout/device-frame', group: 'Components' },
  { label: 'Layout Preview', path: '/layout/layout-preview', group: 'Components' },

  // ===== ADVANCED INTERACTION =====
  { label: 'Virtual Scroll', path: '/virtual-scroll', group: 'Components' },
  { label: 'Virtual Grid', path: '/virtual-grid', group: 'Components' },
  { label: 'Sortable List', path: '/sortable-list', group: 'Components' },
  { label: 'Kanban Board', path: '/kanban', group: 'Components' },
  { label: 'Resizable Panels', path: '/resizable-panels', group: 'Components' },
  { label: 'Column Selector', path: '/column-selector', group: 'Components' },
  { label: 'Filter Builder', path: '/filter-builder', group: 'Components' },
  { label: 'Query Builder', path: '/query-builder', group: 'Components' },
  { label: 'Drag & Drop', path: '/directives/drag-drop', group: 'Components' },
  { label: 'Infinite Scroll', path: '/directives/infinite-scroll', group: 'Components' },

  // ===== COLLABORATION & ACTIVITY =====
  { label: 'Chat', path: '/chat', group: 'Components' },
  { label: 'Command History', path: '/command-history', group: 'Components' },
  { label: 'Version Timeline', path: '/version-timeline', group: 'Components' },
  { label: 'Audit Log', path: '/audit-log', group: 'Components' },
  { label: 'Activity Explorer', path: '/activity-explorer', group: 'Components' },

  // ===== DESIGN TOOLS =====
  { label: 'Color Gradient', path: '/design-tools/color-gradient', group: 'Components' },
  { label: 'Color Gradient Editor', path: '/design-tools/color-gradient-editor', group: 'Components' },
  { label: 'Shadow Editor', path: '/design-tools/shadow-editor', group: 'Components' },
  { label: 'Border Editor', path: '/design-tools/border-editor', group: 'Components' },
  { label: 'Transform Editor', path: '/design-tools/transform-editor', group: 'Components' },
  { label: 'Spacing Editor', path: '/design-tools/spacing-editor', group: 'Components' },
  { label: 'Property Editor', path: '/design-tools/property-editor', group: 'Components' },
  { label: 'Theme Editor', path: '/design-tools/theme-editor', group: 'Components' },
  { label: 'Color Token Generator', path: '/design-tools/color-token-generator', group: 'Components' },

  // ===== DASHBOARD =====
  { label: 'Metric Card', path: '/dashboard/metric-card', group: 'Components' },
  { label: 'Metric Grid', path: '/dashboard/metric-grid', group: 'Components' },
  { label: 'Sparkline Card', path: '/dashboard/sparkline-card', group: 'Components' },
  { label: 'KPI Card', path: '/dashboard/kpi-card', group: 'Components' },
  { label: 'Comparison Card', path: '/dashboard/comparison-card', group: 'Components' },
  { label: 'Goal Progress', path: '/dashboard/goal-progress', group: 'Components' },
  { label: 'Ranking List', path: '/dashboard/ranking-list', group: 'Components' },
  { label: 'Leaderboard', path: '/dashboard/leaderboard', group: 'Components' },
  { label: 'Statistic Group', path: '/dashboard/statistic-group', group: 'Components' },
  { label: 'Dashboard Widget', path: '/dashboard/dashboard-widget', group: 'Components' },

  // ===== DEVELOPER TOOLS =====
  { label: 'HTTP Status', path: '/devtools/http-status', group: 'Components' },
  { label: 'Environment Switcher', path: '/devtools/environment-switcher', group: 'Components' },
  { label: 'Terminal', path: '/devtools/terminal', group: 'Components' },
  { label: 'Log Viewer', path: '/devtools/log-viewer', group: 'Components' },
  { label: 'API Response Viewer', path: '/devtools/api-response-viewer', group: 'Components' },
  { label: 'Request Builder', path: '/devtools/request-builder', group: 'Components' },
  { label: 'Regex Tester', path: '/devtools/regex-tester', group: 'Components' },
  { label: 'Cron Builder', path: '/devtools/cron-builder', group: 'Components' },
  { label: 'Calculator', path: '/devtools/calculator', group: 'Components' },
  { label: 'Code Editor', path: '/devtools/code-editor', group: 'Components' },

  // ===== ENTERPRISE / PRO =====
  { label: 'Advanced Data Grid', path: '/enterprise/advanced-data-grid', group: 'Components' },
  { label: 'Scheduler', path: '/enterprise/scheduler', group: 'Components' },
  { label: 'Gantt Chart', path: '/enterprise/gantt-chart', group: 'Components' },
  { label: 'Permission Matrix', path: '/enterprise/permission-matrix', group: 'Components' },
  { label: 'Pivot Table', path: '/enterprise/pivot-table', group: 'Components' },
  { label: 'Email Template Builder', path: '/enterprise/email-template-builder', group: 'Components' },
  { label: 'File Manager', path: '/enterprise/file-manager', group: 'Components' },
  { label: 'Spreadsheet', path: '/enterprise/spreadsheet', group: 'Components' },
  { label: 'Workflow Builder', path: '/enterprise/workflow-builder', group: 'Components' },
  { label: 'Column Manager', path: '/enterprise/column-manager', group: 'Components' },
  { label: 'Advanced Filters', path: '/enterprise/advanced-filters', group: 'Components' },
  { label: 'Dashboard Builder', path: '/dashboard/dashboard-builder', group: 'Components' },
  { label: 'Widget Grid', path: '/dashboard/widget-grid', group: 'Components' },
  { label: 'Dashboard Filters', path: '/dashboard/dashboard-filters', group: 'Components' },
  { label: 'Prompt Input', path: '/ai/prompt-input', group: 'Components' },
  { label: 'Chat Stream Viewer', path: '/ai/chat-stream', group: 'Components' },
  { label: 'Token Counter', path: '/ai/token-counter', group: 'Components' },
  { label: 'Model Selector', path: '/ai/model-selector', group: 'Components' },
  { label: 'Markdown Code Runner', path: '/ai/code-runner', group: 'Components' },
  { label: 'AI Chat', path: '/ai/chat', group: 'Components' },
  { label: 'AI Prompt Builder', path: '/ai/prompt-builder', group: 'Components' },
  { label: 'AI Response Viewer', path: '/ai/response-viewer', group: 'Components' },
  { label: 'AI Token Usage', path: '/ai/token-usage', group: 'Components' },
  { label: 'AI Model Playground', path: '/ai/model-playground', group: 'Components' },

  // ===== ABOUT =====
  { label: 'Who We Are', path: '/about/who-we-are', group: 'About' },
  { label: 'License', path: '/about/license', group: 'About' },
  { label: 'Contributing', path: '/about/contributing', group: 'About' },
  { label: 'Contact', path: '/about/contact', group: 'About' },

  // ===== BLOCKS =====
  { label: 'Hero Sections', path: '/blocks/hero-sections', group: 'Blocks' },
  { label: 'Headers', path: '/blocks/headers', group: 'Blocks' },
  { label: 'Footers', path: '/blocks/footers', group: 'Blocks' },
  { label: 'Pricing', path: '/blocks/pricing', group: 'Blocks' },
  { label: 'Feature Sections', path: '/blocks/feature-sections', group: 'Blocks' },
  { label: 'Testimonials', path: '/blocks/testimonials', group: 'Blocks' },
  { label: 'CTA Sections', path: '/blocks/cta-sections', group: 'Blocks' },
  { label: 'Login Block', path: '/blocks/login', group: 'Blocks' },
  { label: 'Register Block', path: '/blocks/register', group: 'Blocks' },
  { label: 'Contact Block', path: '/blocks/contact', group: 'Blocks' },
  { label: 'FAQ', path: '/blocks/faq', group: 'Blocks' },
  { label: 'About Block', path: '/blocks/about', group: 'Blocks' },
  { label: 'Team', path: '/blocks/team', group: 'Blocks' },
  { label: 'Newsletter', path: '/blocks/newsletter', group: 'Blocks' },
  { label: 'Blog Block', path: '/blocks/blog', group: 'Blocks' },
  { label: 'Dashboard Block', path: '/blocks/dashboard', group: 'Blocks' },
  { label: 'Statistics Block', path: '/blocks/statistics', group: 'Blocks' },
  { label: 'Landing Pages', path: '/blocks/landing-pages', group: 'Blocks' },

  // ===== TEMPLATES =====
  { label: 'Login Template', path: '/templates/login', group: 'Templates' },
  { label: 'Register Template', path: '/templates/register', group: 'Templates' },
  { label: 'Forgot Password', path: '/templates/forgot-password', group: 'Templates' },
  { label: 'Dashboard Template', path: '/templates/dashboard', group: 'Templates' },
  { label: 'Profile', path: '/templates/profile', group: 'Templates' },
  { label: 'Settings', path: '/templates/settings', group: 'Templates' },
  { label: 'Admin Dashboard', path: '/templates/admin-dashboard', group: 'Templates' },
  { label: 'CRM', path: '/templates/crm', group: 'Templates' },
  { label: 'HR Portal', path: '/templates/hr-portal', group: 'Templates' },
  { label: 'E-commerce', path: '/templates/ecommerce', group: 'Templates' },
  { label: 'Project Management', path: '/templates/project-management', group: 'Templates' },
  { label: 'Analytics Dashboard', path: '/templates/analytics-dashboard', group: 'Templates' },
  { label: 'Risk Management Dashboard', path: '/templates/risk-management', group: 'Templates' },
  { label: 'Document Management', path: '/templates/document-management', group: 'Templates' },
  { label: 'User Management', path: '/templates/user-management', group: 'Templates' },
  { label: 'Notifications Template', path: '/templates/notifications', group: 'Templates' },
];
